//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorsaProjesiAraSinav
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Talep()
        {
            this.KullaniciTalepleri = new HashSet<KullaniciTalep>();
        }
    
        public int Id { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> TalepMiktari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciTalep> KullaniciTalepleri { get; set; }
    }
}
