//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorsaProjesiAraSinav
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.KullaniciUrunleri = new HashSet<KullaniciUrun>();
        }
    
        public int Id { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> BirimFiyat { get; set; }
        public Nullable<int> Onay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciUrun> KullaniciUrunleri { get; set; }
    }
}
